/**
 * Part 2: the starter guidance note, the thirty-day plan, and the boundary
 * sections that define where the bare minimum stops.
 *
 * ---------------------------------------------------------------------------
 * CANONICAL SOURCE CONTENT. DO NOT EDIT WITHOUT SIGN-OFF.
 * Verbatim from "The AI Bare Minimum Pack", Parts 1 and 2.
 *
 * The three worked examples below are the source's own. The tailoring layer may
 * add one generated scenario ALONGSIDE them; it must never replace them.
 * ---------------------------------------------------------------------------
 */

import type { ControlNumber, PlanWeek } from "@/lib/domain/types";

export const WHY_YOU_ARE_BEING_ASKED = [
  "Almost everyone in your organisation is already using AI in one form or another, and the real question is whether anyone is governing it.",
  "This is the bare minimum, eight things that any organisation of any size should have in place before it worries about anything more sophisticated. Get them done and you have removed most of the risk that actually bites, which is data walking out of the door, unverified output reaching a client, and AI use that nobody disclosed.",
];

export const WHAT_THE_BARE_MINIMUM_BUYS_YOU = [
  "Three things, really. Your data stops leaking, nothing reaches a client without a human having checked it, and when someone asks how you govern AI, whether that is a client, an insurer, a funder or a regulator, you have an answer with a date on it.",
  "It also buys you the room to do the full review properly rather than in a panic.",
];

/**
 * "The three things that actually go wrong". These are the source's own worked
 * examples and they always render. A generated risk scenario sits alongside.
 */
export const THREE_THINGS_THAT_GO_WRONG = [
  {
    title: "Data walks out of the door",
    body: "Someone pastes a client contract, a patient record or the management accounts into a free tool that trains on the input. You have made a disclosure you cannot retrieve, and depending on what it was, one you have to report to the Information Commissioner's Office within 72 hours.",
  },
  {
    title: "Unverified output reaches a client",
    body: "Deloitte refunded A$290,000 to the Australian government in 2025 after a report it had been paid A$440,000 for was found to contain fabricated citations and a quotation attributed to a judge who never said it. A second report in Canada had the same problem. Over 600 court cases worldwide now involve lawyers filing AI-invented case law.",
  },
  {
    title: "The AI contribution went undeclared",
    body: "West Midlands Police recommended a ban on away fans based on an intelligence report referencing a match that never took place, generated by Copilot. The Chief Constable first denied AI had been used, then admitted it in a letter to MPs, and retired with immediate effect in January 2026.",
  },
];

export const THE_PATTERN =
  "The pattern is identical every time. AI contributed, nobody verified, nobody declared, and someone outside the organisation found out first. The denial did more damage than the error.";

export const GOVERNING_PRINCIPLE = {
  title: "The governing principle: governance proportionate to risk",
  body: [
    "Governance should be matched to risk, because a grammar-checked email and an AI-drafted board paper are nothing like the same thing and should never carry the same process.",
    "Get this wrong in the heavy direction and people will quietly work around you, which is worse than having no policy at all. So routine work with approved tools and no sensitive data needs nothing beyond professional judgement, and everything else earns a little more attention as the AI contribution and the stakes rise.",
  ],
};

// ---------------------------------------------------------------------------
// The thirty-day plan
// ---------------------------------------------------------------------------

export interface PlanEntry {
  week: PlanWeek;
  label: string;
  /** Verbatim "What you do" cell. */
  whatYouDo: string;
  /** Verbatim "Who" cell. */
  who: string;
  /** Which controls this week's work advances. Drives checklist ordering. */
  controls: ControlNumber[];
}

export const THIRTY_DAY_PLAN_INTRO =
  "This is achievable alongside a normal working month in a small organisation.";

export const THIRTY_DAY_PLAN: PlanEntry[] = [
  {
    week: 1,
    label: "Week 1",
    whatYouDo:
      "Name the AI lead. Ask every team what tools they use. Open the amnesty with a deadline.",
    who: "MD or owner",
    controls: [1, 2, 5],
  },
  {
    week: 2,
    label: "Week 2",
    whatYouDo:
      "Build the register. Decide what is approved, approved with conditions, and not approved. Check data processing terms for anything touching personal data.",
    who: "AI lead",
    controls: [2, 4],
  },
  {
    week: 3,
    label: "Week 3",
    whatYouDo:
      "Fill in the policy. Approve it at your management or board meeting and minute the decision. Issue it with the staff note.",
    who: "AI lead and board",
    controls: [3],
  },
  {
    week: 4,
    label: "Week 4",
    whatYouDo:
      "Run the training hour. Publish the website statement and the email footer. Add note-taker disclosure to the meeting invitation template. Set the quarterly agenda item.",
    who: "AI lead",
    controls: [7, 8],
  },
];

/**
 * The order in which non-red-line controls are worked, taken straight from the
 * thirty-day plan above. Red-line controls (4 and 6) are pinned ahead of this
 * list at ordering time, because the source says so explicitly.
 *
 * Derived from THIRTY_DAY_PLAN so the two can never drift apart.
 */
export const PLAN_CONTROL_ORDER: ControlNumber[] = Array.from(
  new Set(THIRTY_DAY_PLAN.flatMap((entry) => entry.controls)),
);

// ---------------------------------------------------------------------------
// The boundary: where the bare minimum stops and the full review begins
// ---------------------------------------------------------------------------

/** Part 1, "What this does not cover". */
export const WHAT_THIS_DOES_NOT_COVER = [
  "The eight points are the bare minimum, and they will not tell you whether your AI use sits inside your risk appetite, whether your board has the competence to oversee it, or whether you are ready for the EU AI Act, ISO 42001 or your own regulator.",
  "On the EU AI Act specifically, the training and reporting obligations are covered here in principle, through the training in point 8 and the register and incident log in points 2 and 8. Whether the Act reaches you at all, and what else it asks of you if it does, needs a fuller review.",
  "Those questions belong to a full governance of AI review, which looks at your use cases, your risk appetite, your board capability, your vendor arrangements, and the assurance your directors receive. The bare minimum buys you the time to do that properly.",
];

/**
 * Part 2, "What the bare minimum does not give you".
 * This is the argument for the Full Playbook, in the source's own words.
 * The Full Playbook pathway must be built from these, never from sales copy.
 */
export const WHAT_THE_BARE_MINIMUM_DOES_NOT_GIVE_YOU = {
  intro:
    "Be clear about the limits, because closing the eight points is only the bare minimum, and a full governance of AI review goes considerably further:",
  items: [
    {
      title: "Risk appetite",
      body: "Your risk appetite and tolerance for AI, agreed and written down, so decisions stop being made case by case.",
    },
    {
      title: "Board and leadership capability",
      body: "Whether the people overseeing this understand enough to challenge what they are told.",
    },
    {
      title: "Use case assessment",
      body: "Which parts of your business AI should touch, which it should not, and what value you are actually getting.",
    },
    {
      title: "Regulatory readiness",
      body: "Whether the EU AI Act reaches you at all, what the Article 50 transparency duties mean for your work from 2 August 2026, how the deferred high-risk timetable of December 2027 changes your plans, and whether ISO 42001 certification earns its keep for an organisation your size. The training and reporting duties are covered in principle by this pack, and everything else there needs a proper look.",
    },
    {
      title: "Vendor and supply chain due diligence",
      body: "Including the AI your suppliers use on your data.",
    },
    {
      title: "Assurance",
      body: "Moving your board from comfort, meaning a framework exists, to confidence, meaning it is demonstrably operating, to conviction, meaning the data proves it.",
    },
  ],
  outro:
    "None of that is urgent this month, though all of it matters within the year.",
};

export const ONE_RULE_TO_REMEMBER = {
  title: "One rule to remember",
  body: "When you are unsure, disclose, because every case that has damaged an organisation over AI has the same anatomy: AI was used, nobody checked it, nobody declared it, and somebody outside found out first. The cover-up always costs more than the disclosure.",
};

export const CLOSING_THOUGHT =
  "Every organisation damaged by AI so far had plenty of capability and very little governance. A month of unglamorous work now is worth more than any tool you could buy.";

// ---------------------------------------------------------------------------
// Footer, disclaimer and trademarks. Reproduced verbatim; do not reword.
// ---------------------------------------------------------------------------

export const PACK_FOOTER = {
  disclaimer:
    "The AI Bare Minimum Pack, a starting point for small organisations, which does not constitute legal advice.",
  fullReview: "For a full governance of AI review, contact karl@tgf.global.",
  builtOn: "Built on The AI Transparency Framework™ by Karl George MBE.",
  organisation:
    "Governance AI  |  governanceai.io  |  GovernAI Academy  |  governaiacademy.com",
  trademarks:
    "The AI Transparency Index™ and The AI Transparency Framework™ are trademarks of Karl George / The Governance Forum.",
};
